[build]
  command = ""
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/women-safety-alert"
  to = "/.netlify/functions/women-safety-alert"
  status = 200

[[redirects]]
  from = "/api/cyber-crime-alert"
  to = "/.netlify/functions/cyber-crime-alert"
  status = 200
